# Generated by Django 4.1.6 on 2023-02-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_genration_02_parent_slug_genration_02_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genration_01',
            name='slug',
            field=models.SlugField(choices=[('appala-naidu', 'appalanaidu'), ('brother-2', 'brother2'), ('pothala-1', 'pothala1'), ('venalapalem-2', 'sister2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='genration_02',
            name='parent_slug',
            field=models.SlugField(choices=[('appala-naidu', 'appalanaidu'), ('brother-2', 'brother2'), ('pothala-1', 'pothala1'), ('venalapalem-2', 'sister2')], max_length=20),
        ),
    ]
