# Generated by Django 4.1.6 on 2023-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_genration_01_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genration_02',
            name='gen_code',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'Two'), (3, 'Three'), (4, 'Three')]),
        ),
    ]
